// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8t9VaEGckhV1KQEN-NzAU_KcRU4scck',
    appId: '1:1016616217443:web:c8d44e8f22256349944156',
    messagingSenderId: '1016616217443',
    projectId: 'fetprojet',
    authDomain: 'fetprojet.firebaseapp.com',
    storageBucket: 'fetprojet.appspot.com',
    measurementId: 'G-J4Z5FYTKSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0z-lFai8lJ2peD4i5onDR8CFvcc9znY',
    appId: '1:1016616217443:android:cb3c86d265dd3dfe944156',
    messagingSenderId: '1016616217443',
    projectId: 'fetprojet',
    storageBucket: 'fetprojet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKhAVC9hRAKZy65m6RInyN1s8QyXxG4U',
    appId: '1:1016616217443:ios:560bba017e73e7a1944156',
    messagingSenderId: '1016616217443',
    projectId: 'fetprojet',
    storageBucket: 'fetprojet.appspot.com',
    iosClientId: '1016616217443-d6no7vbpgmm5u82mbj1gq7e6s25vd6nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fetprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKhAVC9hRAKZy65m6RInyN1s8QyXxG4U',
    appId: '1:1016616217443:ios:560bba017e73e7a1944156',
    messagingSenderId: '1016616217443',
    projectId: 'fetprojet',
    storageBucket: 'fetprojet.appspot.com',
    iosClientId: '1016616217443-d6no7vbpgmm5u82mbj1gq7e6s25vd6nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fetprojet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ8t9VaEGckhV1KQEN-NzAU_KcRU4scck',
    appId: '1:1016616217443:web:1dc2f76442de79e5944156',
    messagingSenderId: '1016616217443',
    projectId: 'fetprojet',
    authDomain: 'fetprojet.firebaseapp.com',
    storageBucket: 'fetprojet.appspot.com',
    measurementId: 'G-SKF5KJMQ6Q',
  );
}
